[project]
name = "laminar-flow"
version = "0.1.0"
description = "Lightweight task engine for building AI agents"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "ipykernel>=6.29.5",
    "lmnr[all]>=0.4.40",
    "openai>=1.55.0",
    "pydantic>=2.10.1",
    "pytest>=8.3.3",
]
